Fix/116/change error messages in update fact handler and tests
project-studying-dotnet/Streetcode-Admin-March-01 pull request #118
Opened 2024-03-28 20:24 UTC by OlhaPivniuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-03-28 23:18 UTC, HlibBondarev approved these changes
Ok

2024-03-29 14:58 UTC, yaninavoda requested changes
Why is ReorderFacts deleted from the FactController?

2024-03-29 14:58 UTC, yaninavoda commented on Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/FactController.cs
> -    [HttpPut]
Why is this deleted?

2024-03-29 19:23 UTC, OlhaPivniuk commented on Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/FactController.cs
> -    [HttpPut]
I put it after UpdateFactDto

2024-03-29 19:31 UTC, OlhaPivniuk commented on Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/FactController.cs
> -    [HttpPut]
I put it after UpdateFactDto to have order Post, Put, Put, Delete (not Put, Post, Put, Delete as we had earlier)

2024-03-30 11:41 UTC, yaninavoda approved these changes
ok

2024-03-30 11:42 UTC, merged