Feat/245/implement refresh token logic
project-studying-dotnet/Streetcode-Admin-March-01 pull request #281
Opened 2024-04-18 19:57 UTC by NMarteniuk

**### Add this code to your user secrets file**
`"RefreshToken": {
  "ExpirationDays": 10
}`

2024-04-18 20:47 UTC, yaninavoda approved these changes
You owe us an explanation)

2024-04-18 21:01 UTC, OlhaPivniuk approved these changes

2024-04-19 05:51 UTC, yaninavoda requested changes
![failure](https://github.com/project-studying-dotnet/Streetcode-Admin-March-01/assets/72311088/d9feac45-726b-40fe-84d6-918d6221330d)

2024-04-19 07:36 UTC, yaninavoda approved these changes

2024-04-19 07:38 UTC, merged