Task - relocate all sensitive data to User Secret (file secrets.json)
project-studying-dotnet/Streetcode-Admin-March-01 pull request #3
Opened 2024-03-15 13:21 UTC by HlibBondarev

Attention!!! 
After you uploaded branch develop with all changes described in the Manual (https://github.com/project-studying-dotnet/Streetcode-Admin-March-01/issues/2#issuecomment-1999603492) all of you need is to fill your secrets.json (like in pic_2 in the Manual - [secrets.json](https://github.com/project-studying-dotnet/Streetcode-Admin-March-01/files/14615624/secrets.json)).
You don't need to do all other actions described in the Manual.

2024-03-15 14:53 UTC, OlhaPivniuk approved these changes
Checked. Done

2024-03-15 15:31 UTC, yaninavoda approved these changes

2024-03-16 11:14 UTC, OlhaPivniuk requested changes
Delete data from .env file

2024-03-16 11:33 UTC, closed without merging

2024-03-16 11:37 UTC, HlibBondarev commented
Before pull-request this branch has to add file - replacements.txt. It contains instructions for deleting or changing repository history information.