Implement Create functionality for Sources block
project-studying-dotnet/Streetcode-Admin-March-01 pull request #90
Opened 2024-03-24 17:04 UTC by yaninavoda

## Summary of issue

Implement Create functionality for Sources block

## Summary of change

add CreateCategoryCommand
add CreateCategoryHandler
add httpPost action CreateCategory to SourcesController
add unit tests

2024-03-27 06:48 UTC, NMarteniuk approved these changes

2024-03-27 07:49 UTC, HlibBondarev requested changes
Сhange the exception message in Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateCategoryHandler.cs

2024-04-01 22:27 UTC, OlhaPivniuk approved these changes

2024-04-02 09:53 UTC, HlibBondarev approved these changes
Ok

2024-04-02 10:55 UTC, merged